### ISSUE TITLE
PM2.5, PM10 history for Air Quality Sensor?

### ISSUE THREAD

**Issue by mrdc** [arachnetech/homebridge-mqttthing#162]
Hello,

Would be nice to add history for PM2.5, PM10 as it's useful for monitoring air quality.

**Comment by tobekas** [comment]
Unfortunately it’s not possible to implement generic history for any kind of data. Since this feature is based on fakegato-history, only some types are possible: only types Elgato Eve supports for their own products. It’s up to Eve, which types are supported. The trick is to fake exactly the bahavior of their custom HomeKit characteristic, to offer the graphics also for homebridge-mqttthing accessories.

**Comment by tobekas** [comment]
For AirQuality sensors, you can just use AirQualityPPM somehow, which is uses by „Eve Room“. You may play around with scaling (apply feature) and just use this topic for your particulate matter (PM) data. If you want to have 2 graphs both for pm2.5 and pm10, you have to configure two separate accessories.

**Comment by mrdc** [comment]
@tobekas 
> For AirQuality sensors, you can just use AirQualityPPM somehow

I did the following:
```json
            "topics": {
                "getAirQuality": {
                    "topic": "/ESP_Easy/PMS7003/pm10",
                    "apply": "co2 = JSON.parse(message); return (co2 > 45 ? 'POOR' : co2 > 40 ? 'INFERIOR' : co2 > 35 ? 'FAIR' : co2 > 25 ? 'GOOD' : co2 <= 25 ? 'EXCELLENT' : 'UNKNOWN');"
                },
                "getCarbonDioxideLevel": "/ESP_Easy/PMS7003/pm10",
                "getAirQualityPPM": "/ESP_Easy/PMS7003/pm10"
            },
            "airQualityValues": [
                "UNKNOWN",
                "EXCELLENT",
                "GOOD",
                "FAIR",
                "INFERIOR",
                "POOR"
            ],
            "history": "true"
        },
```

This is my default AirQuality Sensor:
![image](https://user-images.githubusercontent.com/16876990/67404548-39916f00-f5bc-11e9-9624-ecd644ea0e6e.png)
Here are 2 AirQuality Sensors for PM2.5&PM10. Unfortunately, there is no charts with the above config for PM2.5&PM10, but measurements are saved:
![image](https://user-images.githubusercontent.com/16876990/67404656-5f1e7880-f5bc-11e9-83f6-d3622d42735e.png)
![image](https://user-images.githubusercontent.com/16876990/67404668-65acf000-f5bc-11e9-9ef4-466100702a63.png)
![image](https://user-images.githubusercontent.com/16876990/67404681-69d90d80-f5bc-11e9-9ce6-733925434e66.png)
![image](https://user-images.githubusercontent.com/16876990/67404694-6e052b00-f5bc-11e9-896d-9c7dbf3bc6f0.png)
![image](https://user-images.githubusercontent.com/16876990/67404775-883f0900-f5bc-11e9-9d5d-59a30d1fd24d.png)

**Comment by Andi1968** [comment]
Hi,
what do the messages look like that you receive under topic /ESP_Easy/PMS7003/pm10 ?
Apparently they are not just ppm values but perhaps some value followed by unit ?
Your Apply always returns UNKNOWN and I suppose Eve App simply interprets this as no measurement available (for the chart). Also the values in the list are not plausible. Even outside you should not see values below 400ppm CO2. Indoors the value should be higher.

Andreas

**Comment by mrdc** [comment]
> Hi,
> what do the messages look like that you receive under topic /ESP_Easy/PMS7003/pm10 ?

Hi,
![image](https://user-images.githubusercontent.com/16876990/67420557-820a5600-f5d7-11e9-9386-6a90295f6a60.png)
Values are loaded normally from the topic - check the first pic where you can see CO2, PM2.5 and PM10, 
For PM2.5&PM10 history I've decided to make a trick and connect PM2.5&PM10 to PPM (2 more AirQuality Stations), so history is saved and EVE app reads PPM values which are taken from PM2.5&PM10 topics.
> Your Apply always returns UNKNOWN
> Even outside you should not see values below 400ppm CO2.
That's strange, because I see that on the main screen in EVE app it returns the correct name like excellent, good etc. Picture below. Don't now why in measurements it shows UNKNOWN. I'll play with my config. Yes, EVE app can drop values <400ppm as incorrect.
![image](https://user-images.githubusercontent.com/16876990/67420723-d6add100-f5d7-11e9-857b-b1c46c4b9e74.png)

**Comment by tobekas** [comment]
Maybe the values around ~10 are too low. This AirQuality history is originally just for displaying VOC values, which are much higher. Can you just try to scale your values by *100 (apply), just to see if the graph is working. By the way, the named categories (UNKNOWN, ...) in the measurements are not related to the AirQuality category characteristic, but derived from the values. There is a fix relation (from Eve’s side) between ppm values and the category.
Nevertheless there is this redundant AirQuality characteristic, because this is a standard HomeKit characteristic, whereas this specific VOC(ppm) characteristic is not.

**Comment by tobekas** [comment]
Maybe you go better with misusing a temperatureSensor type. Of course this is very unpleasant, because you will get unit °C. But this is just as wrong as ppm instead of μg/m^3.

As a long-term solution I recommend you to take a look at Grafana, a great plattform for MQTT logging and many more. There is a big community and it can also run on a RPi.

**Comment by mrdc** [comment]
> Maybe you go better with misusing a temperatureSensor type. Of course this is very unpleasant, because you will get unit °C. But this is just as wrong as ppm instead of μg/m^3.
> 
> As a long-term solution I recommend you to take a look at Grafana, a great plattform for MQTT logging and many more. There is a big community and it can also run on a RPi.

Thanks, I'll try to scale and then will try with the TempSensor. Grafana is great, but there is no iOS app and devs don't plan to release it, additionally my family members like EVE app :)
