### ISSUE TITLE
Security System - refresh current state

### ISSUE THREAD

**Issue by iondarie** [arachnetech/homebridge-mqttthing#165]
Hello,

I am using your plugin to control my alarm but i have a small problem.

I arm the system from my phone when i leave home, when my wife arrives home she disarms the system using the Paradox TM70 keypad. The script connecting the paradox alarm and your plugin immediately detects the disarm and publishes to: "getCurrentState": "paradox/states/partitions/Parter/current_state" the disarmed state but the plugin ignores this state and now homekit shows the alarm as arming and continuously spinning.

If we arm/disarm only via homekit there are no problems, it seems the problem appears only when arming/disarming from the keypad.

Can a refresh of the current state be implemented or something that might fix this issue?

Thank you,

**Comment by arachnetech** [comment]
Your script should publish getTargetState too, to inform Homekit of the new target state - otherwise Homekit assumes that your alarm system will still be trying to reach its target state (hence the spinning).

**Comment by dzonatan** [comment]
Does not work for me either. Even when publishing the new target state to both topics `getTargetState` and `getCurrentState` - homekit still shows a pending action (disarming/arming...).
Although it works when publishing to `setTargetState` externally - but I guess that's not the way it was designed to be used (also I haven't tested this on the actual system, only manually by sending mqtt message)?
And it looks like `getTargetState` has no real purpose at the moment - it does not matter what messages you are sending, homekit does not react to them in any way.

**Comment by psyciknz** [comment]
Isn’t the issue that the target state isn’t the exact same as the actual.

I noticed this also (also using pai for paradox).  If I arm via keypad/remote.  Hb gets the armed_away state but then seems to report as disarming after a period of time.

The last action that hb did on the alarm might have been a disarm  command (ends up with a disarmed state).   And it figured that out, but there’s something in the refresh that seems to be making it remember that it has previously asked for disarm.

Is there a way of on state changed, reset all target states?

**Comment by dzonatan** [comment]
It does not work correctly with PAI at the moment because it's using a different `targetStateValues` and `currentStateValues` values. So you cannot use the same topic for `getTargetState` and `getCurrentState` as it's declared in this documentation. 
Plugin does not know what to do with "current state" values when they come in `getTargetState` topic.
Take a look at PAI homebridge config https://github.com/ParadoxAlarmInterface/pai/wiki/Homebridge
```
            "topics": {
                "setTargetState": "paradox/control/partitions/First_floor",
                "getTargetState": "paradox/states/partitions/First_floor/current_state",
                "getCurrentState": "paradox/states/partitions/First_floor/current_state"
            },
            "currentStateValues": [
                "armed_home",
                "armed_away",
                "armed_night",
                "disarmed",
                "triggered"
            ],
            "targetStateValues": [
                "arm_stay",
                "arm",
                "arm_sleep",
                "disarm"
            ],
```
`getTargetState` expects values from `targetStateValues`.

This looks more like an issue on PAI side - there should be a separate topic which would broadcast "target state" value when system is arming/disarming externally. Or.. target and current state values have to be unified.

**Comment by psyciknz** [comment]
But isn’t MQTTthing using the getcurrentstate once pai has set a value?   As in it’s noticed a change, there should be no need to care about target state.

Would the issue be fixed if pai used the same value for current and target (ie disarm for command and state, rather than disarmed.  Or arm_away for both rather than armed_away)?

I do work on pai as well but haven’t for a few weeks.

**Comment by dzonatan** [comment]
If I understood correctly homekit always needs to know two values:
- TARGET - What is the target that system is trying to be in.
- CURRENT - What is the current system state.

Everytime when TARGET != CURRENT you will see "disarming" or "arming".

So it's not enough to change only **current** value as homekit needs to know what is the **target** as well. Currently with PAI when you arm the system through keypad only **current** status is changed (because `getTargetState` does not understand values coming form current state). Therefore you see "disarming/arming" because the target was not updated..
It didn't sound logical to me at first either - but now it does.

If states values are unified - it might work. But if I'm not mistaken - PAI does not broadcast any topic when user initiates arming through keypad. You will get status update when arming is completed - so you won't see those intermediate "arming"/"disarming" states (only when using keypad).

**Comment by psyciknz** [comment]
I think pai does know arming/state.
`
2019-11-13 23:01:58,234 - WARNING  - PAI.paradox.paradox - Missing type special for event: 30.3 Partial arming
WARNING:PAI.paradox.paradox:Missing type special for event: 30.3 Partial arming
`

But I still can’t figure out why only once the lance is externally armed, why hb insists it’s disarming.   When panel disarmed externally hb reports  the correct state. I dint know enough nodejs but will look, surely the target state should be taken from current wherever it’s changed, just so they always match.  And there should only be a deviation when the user tries to modify the state via HomeKit

**Comment by dzonatan** [comment]
| But I still can’t figure out why only once the panel is externally armed, why hb insists it’s disarming. 
Because **target** and **current** states do not match.
Read my comment again. You didn't get my explanation. :)

Let's say the system is unarmed and homekit shows that correctly. So it holds two values:
- target:`disarm`
- current: `disarmed`

When you arm your system externally through keypad, only **current** value is changed at the moment with PAI so the values become:
- target: `disarm`
- current: `armed`

Which means that homekit still thinks you want to be disarmed (look at the target state!), but you're currently - therefore it shows you the pending "disarming..." state.

**Comment by psyciknz** [comment]
but if getCurrentState and getTargetstate are the same topic, isn't target and current now the externally set value of `armed`

**Comment by dzonatan** [comment]
Yes, you're right - but it only makes sense when these two topics share the same values.
In case of PAI - `targetStateValues` and `currentStateValues` has different values.
So when `armed`/`disarmed` value comes to `getTargetState` - it does not ring any bell for homebridge - it just do not know what it means. It expects `arm`/`disarm` (just like HB publishes it to `setTargetState`).

**Comment by psyciknz** [comment]
So if we can get pai to post disarm for the state and the Accept disarm as a command then it should work as expected?

**Comment by psyciknz** [comment]
OK so yes it works.....Configs as below.
`
 {
            "accessory": "mqttthing",
            "type": "securitySystem",
            "name": "Alarm-HB",
            "url": "<mqtt server>",
            "caption": "Alarm-HB",
            "logMqtt": true,
            "topics": {
                "setTargetState": "paradox/control/partitions/<partition>/current",
                "getTargetState": "paradox/states/partitions/<partition>/current",
                "getCurrentState": "paradox/states/partitions/<partition>/current"
            },
            "targetStateValues": [
                "arm_stay",
                "arm_away",
                "arm_sleep",
                "disarm"
            ],
            "currentStateValues": [
                "arm_home",
                "arm_away",
                "arm_night",
                "disarm",
                "triggered"
            ],
            "restrictTargetState": [
                1,
                2,
                3
            ]
        }
`

Note the preset tense on the command (no mis or past and present = arm not armed).

Then in PAI add the following:
`
# MQTT Homebridge
MQTT_HOMEBRIDGE_ENABLE = True

# Topic to use
# Defaults to paradox/states/partitions/PARTITION/current
MQTT_HOMEBRIDGE_SUMMARY_TOPIC = 'current'

# Homebridge states map
# Key = Paradox State
# Value = State propagated to Homebridge
MQTT_PARTITION_HOMEBRIDGE_STATES = dict(
    alarm='triggered',
    stay_arm='arm_stay',
    arm='arm_away',
    sleep_arm='arm_sleep',
    disarm='disarm')
# Homebridge control map
# Key = Command from Homebridge
# Value = Command sent to Panel
MQTT_PARTITION_HOMEBRIDGE_COMMANDS = dict(
    STAY_ARM='arm_stay',
    AWAY_ARM='arm_away',
    NIGHT_ARM='arm_sleep',
    DISARM='disarm')
`

Again note the present tense for everything.  I have homebridge now turned on as well as hass.  It's a variance of the topic (paradox/states/partitions/PARTITION/current_hass for home assistant and paradox/states/partitions/PARTITION/current for homebridge).

Mine has just armed via remote, and it's set correctly in the home at as away.

**Comment by timsdrew** [comment]
@psyciknz does this still work for you? What panel do you have? I have SP6000 via ip150 and cannot get it to work by using your settings.

**Comment by dzonatan** [comment]
@timsdrew I didn't provide any working config in this issue. :)
However, if you want to use homebridge you should probably be using dev branch from https://github.com/ParadoxAlarmInterface/pai/tree/dev

**Comment by timsdrew** [comment]
@dzonatan thanks I have it working with the master build, but getting the spinning "arming" when disarming via remote or keypad.

**Comment by dzonatan** [comment]
This is fixed in dev branch.

**Comment by psyciknz** [comment]
> @psyciknz does this still work for you? What panel do you have? I have SP6000 via ip150 and cannot get it to work by using your settings.

Yes, mine has been fine since i made those changes.....but I may be rocking a variation on the PAI dev branch - or from my own fork.....yeah I am, the PAI docker image I'm using is my own, so it could be have some of the parts from the dev branch as I was developing a homie integration.
