### ISSUE TITLE
Accept bare JS booleans

### ISSUE THREAD

**Issue by jdtsmith** [arachnetech/homebridge-mqttthing#218]
`zigbee2mqtt` encodes bare JS tokens `true` and `false` in its MQTT message payloads, e.g.:

```
MQTT publish: topic 'zigbee2mqtt/aqara_motion_lux_1', payload '{"battery":100,"voltage":3035,"illuminance":24,"illuminance_lux":24,"linkquality":60,"occupancy":true}'
```

`JSON.parse` dutifully renders these as pure boolean values.  For its own booleans, it would be very helpful if `mqttthing` would accept not just the string `"true"` and `"false"`, but the bare JS boolean tokens as well.

**Comment by arachnetech** [comment]
Yes, good idea. You could 'solve' it in the apply function by wrapping the result in ( ) ? 'true' : 'false', but it would make sense if Boolean things could accept true and false directly too.

**Comment by jdtsmith** [comment]
Thanks.  Yeah I have done exactly that:

```
 "apply": "return JSON.parse(message).occupancy?'true':'false'"
```

But I see others have been confused by this as well (e.g. #100), and resorted to integer values.

**Comment by arachnetech** [comment]
... or even just `"apply": "return '' + JSON.parse(message).occupancy`

There's a very easy way to implement this (allowing mqttthing to accept `true` and `false` as returned by the apply function), but I'm concerned that it will then become inconsistent - because when publishing within JSON we'll still publish `"true"` and `"false"`.

I think it would be better to allow non-string values everywhere and only perform automatic conversion to/from string when *not* using apply functions. However this is a larger change and might affect existing behaviour in some situations.

**Comment by jdtsmith** [comment]
Other situations besides `apply`?  Do you mean internal to the code?  Couldn't you just test `apply` return values for truthiness as `ret == "true" || ret===true`?

**Comment by arachnetech** [comment]
Sorry, I wasn't clear: I mean it seems inconsistent if the code can receive `true` and `false` as bare JS Booleans but when it publishes them it publishes them as `"true"` and `"false"` strings. I think Boolean values should be passed to an apply function used for publishing as bare JS Booleans too, not strings as now.

**Comment by jdtsmith** [comment]
That makes sense.  Perhaps you could add another config keyword "booleanValue" or some such, for receiving/publishing bare boolean values.  Thus it wouldn't break anything, and your docs would have some information reminding people that `"true" !== true`, to prevent the sort of confusion seen in #100 (and for a while by me!).

**Comment by arachnetech** [comment]
Yes, I could add yet another configuration setting. I'm hoping I can make it sufficiently compatible that it will be fine without requiring that.

**Comment by arachnetech** [comment]
Changed in 1.1.1.
