### ISSUE TITLE
Door / Window sensor

### ISSUE THREAD

**Issue by mientki** [arachnetech/homebridge-mqttthing#27]
Hello
I bought a door / window opening sensor such as here:
https://www.aliexpress.com/item/SECRUI-D026-Window-Door-Magnet-Sensor-Detector-Portable-Alarm-Sensors-Smart-Home-Detectors-Wireless-For-SECRUI/32891067687.html?spm=a2g0s.9042311.0.0.27425c0fBEEiyB

The sensor supports 3 RF codes: closed, open and tampered. I've paired the sensor with Sonoff RF Bridge with Tasmota. When I open physically, I close the sensor so I have in the console, respectively:

```
21:11:33 MQT: tele/rf-bridge/RESULT = {"RfReceived":{"Sync":9560,"Low":320,"High":940,"Data":"81FEE7","RfKey":3}}
21:11:42 MQT: tele/rf-bridge/RESULT = {"RfReceived":{"Sync":9560,"Low":320,"High":940,"Data":"81FEEE","RfKey":4}}
21:11:47 MQT: tele/rf-bridge/RESULT = {"RfReceived":{"Sync":9530,"Low":320,"High":940,"Data":"81FEEB","RfKey":5}}
```

Where:
Rf3 = open
Rf4 = closed
Rf5 = tempered

How do I set the topics in the plugin configuration to make it work properly? My config:

```
        {
            "accessory": "mqttthing",
            "type": "contactSensor",
            "name": "sensor1",
            "url": "mqtt://192.168.99.170",
            "username": "",
            "password": "",
            "caption": "",
            "topics": {
                "getContactSensorState": "cmnd/rf-bridge/RfKey3",
                "getStatusActive": "",
                "getStatusFault": "",
                "getStatusTampered": "",
                "getStatusLowBattery": ""
            },
            "integerValue": "",
            "onValue": "ON",
            "offValue": "OFF"
        }
```

**Comment by arachnetech** [comment]
I believe you can now do this with https://github.com/arachnetech/homebridge-mqttthing#applying-functions-to-mqtt-messages-custom-payload-encodingdecoding.

**Comment by lulek2007** [comment]
Hi,

I have a very similar configuration.
`{
    "accessory": "mqttthing",
    "type": "contactSensor",
    "name": "sensor_1",
    "url": "mqtt://192.168.4.10",
    "username": "admin",
    "password": "123456",
    "caption": "sonoff_rf",
    "topics":
    {
        "getContactSensorState": {
    	    "topic": "tele/sonoff_rf/RESULT",
            "apply": "return  JSON.parse(message).RfReceived.Data;"
        }
    },
    "onValue": "6F5321",
    "offValue": "79FAE1",
    "logMqtt": true    
    }`

my sonoff rf bridge in the console show 

13:37:11 MQT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12380,"Low":400,"High":1210,"Data":"79FAE1","RfKey":"None"}}
13:37:13 MQT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12420,"Low":400,"High":1210,"Data":"6F5321","RfKey":"None"}}

and homebridge logMqtt show 

[1/20/2019, 1:01:25 PM] [sensor_11] Received MQTT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12390,"Low":400,"High":1210,"Data":"79FAE1","RfKey":"None"}}                                             
[1/20/2019, 1:01:28 PM] [sensor_1] Received MQTT: tele/sonoff_rf/RESULT = {"RfReceived":{"Sync":12410,"Low":400,"High":1210,"Data":"6F5321","RfKey":"None"}}   

the problem is that the "onValue" option: "6F5321" works properly and triggers sensor_1 "open" while the "close" state triggers "offValue": "79FAE1" or any value eg "offValue": "111111".

This means that you can not assign specific 2 values to a specific sensor.

"offValue": "111111" or "offValue": "79FAE1" close all sensors

Can I ask for help in proper configuration

Regards 

Marcin Kowalik
