### ISSUE TITLE
RF Door Bell with Sonoff RF Bridge Config....

### ISSUE THREAD

**Issue by JimmyEyeball** [arachnetech/homebridge-mqttthing#274]
I'm having an issue getting an RF Door Bell working through a Sonoff RF Bridge I'm assuming its a config issue I have tried a few combinations of the config with no success I'll post my attempt if someone could please point me in the right direction it would be much appreciated...

**_Log From Bridge:_**
12:46:22 MQT: tele/RF/RESULT = {"Time":"2020-05-24T12:46:22","RfReceived":{"Sync":10310,"Low":380,"High":1000,"Data":"F1FB61","RfKey":"None"}}
12:46:55 MQT: tele/RF/RESULT = {"Time":"2020-05-24T12:46:55","RfReceived":{"Sync":12590,"Low":460,"High":1220,"Data":"F9754E","RfKey":"None"}}

**_HB Logs:_**

May 24 14:36:09 raspberrypi homebridge[2022]: [5/24/2020, 14:36:09] [Door Bell] Initializing mqttthing accessory...
May 24 14:36:09 raspberrypi homebridge[2022]: [5/24/2020, 14:36:09] [Door Bell] MQTT URL: mqtt://192.168.1.173
May 24 14:36:09 raspberrypi homebridge[2022]: [5/24/2020, 14:36:09] [Door Bell] MQTT options: {"keepalive":10,"clientId":"mqttthing_Door Bell_52345ecb","protocolId":"MQTT","protocolVersion":4,"clean":true,"reconnectPeriod":1000,"connectTimeout":30000,"will":{"topic":"WillMsg","payload":"Connection Closed abnormally..!","qos":0,"retain":false},"username":"1111","rejectUnauthorized":false}
May 24 14:36:10 raspberrypi homebridge[2022]: [5/24/2020, 14:36:10] [Door Bell] Exception while creating services: TypeError: Cannot read property 'resubscribe' of undefined
May 24 14:36:10 raspberrypi homebridge[2022]: [5/24/2020, 14:36:10] [Door Bell] Accessory mqttthing returned empty set of services. Won't adding it to the bridge!

**_Config:_**

```json
{
			"accessory": "mqttthing",
			"type": "doorbell",
			"name": "Door Bell",
			"url": "mqtt://192.168.1.173",
			"username": "1111",
			"password": "1111",
			"caption": "Front Door Bell",
			"topics": {
				"getSwitch": [{
					"topic": "tele/RF/RESULT",
					"apply": "return JSON.parse( message ).RfReceived.Data;"
				}]
			},
			"switchValues": [
				["F1FB61"]
			],
			"restrictSwitchValues": [
				0
			],
			"logMqtt": true
		}
```

**Comment by JimmyEyeball** [comment]
Any Ideas Guys...

**Comment by rbswift** [comment]
Maybe you need to have all three values specified in "switchValues"? Try adding a couple of dummy values?

There is a similar config here that you can probably use as a guide... https://github.com/arachnetech/homebridge-mqttthing/wiki/Tested-Configurations#konke-multi-function-button

**Comment by arachnetech** [comment]
Interesting - something's not happy:

> May 24 14:36:10 raspberrypi homebridge[2022]: [5/24/2020, 14:36:10] [Door Bell] Exception while creating services: TypeError: Cannot read property 'resubscribe' of undefined

I'll try running your config here later. Alternatively, the latest release should give a stack trace which should point at the source of this error.

**Comment by arachnetech** [comment]
I believe the problem is that you have an extraneous pair of `[]` around the `getSwitch` topic. StatelessProgrammableSwitch supports an array of topics in `getSwitch` to allow multiple buttons to be created in a single switch, but Doorbell doesn't support this.

I just tested with:

```json
{
    "accessory": "mqttthing",
    "type": "doorbell",
    "name": "Door Bell",
    "url": "homebridge",
    "caption": "Front Door Bell",
    "topics": {
        "getSwitch": {
            "topic": "tele/RF/RESULT",
            "apply": "return JSON.parse( message ).RfReceived.Data;"
        }
    },
    "switchValues": [
        ["F1FB61"]
    ],
    "restrictSwitchValues": [
        0
    ],
    "logMqtt": true
}
```

... and while initially I thought Homekit wouldn't like it (it seems to show doorbells as unsupported, I think unless they support video too):

![image](https://user-images.githubusercontent.com/24389384/83975192-6e9fc700-a8ea-11ea-9926-d7c45c95f33c.png)

... when I trigger the doorbell with:

`mosquitto_pub -h homebridge -t "tele/RF/RESULT" -m '{"Time":"2020-05-24T12:46:22","RfReceived":{"Sync":10310,"Low":380,"High":1000,"Data":"F1FB61","RfKey":"None"}}'`

... I get a notification:

![image](https://user-images.githubusercontent.com/24389384/83975207-8d9e5900-a8ea-11ea-983b-12df9bead485.png)
