### ISSUE TITLE
Can codecs set topics, and what happens to notify(X) without matching getX topic?

### ISSUE THREAD

**Issue by jdtsmith** [arachnetech/homebridge-mqttthing#340]
Working on a codec for control of IKEA blinds via [Zigbee2MQTT](https://github.com/Koenkk/zigbee2mqtt).  Is it kosher for a codec to take e.g. a `topicBase` config item, and then set type and all the topics itself in the codec's `init`, ala:

```JS
function init( params ) {
  let { log, config, publish, notify } = params;
  ...
  config.type = "windowCovering"
  config.topics={"getTargetPosition":config.topicBase,
		 "getBatteryLevel":config.topicBase,
		 "getCurrentPosition":config.topicBase,
		 "setTargetPosition":config.topicBase + "/set/position"}
  ...
  return {decode,encode}
}


```

This seems to work fine, and is very convenient, but isn't documented.  

Also, for properties which all respond to the same MQTT topic,  if you omit for example a `getBatteryLevel` topic, what happens to `notify('batteryLevel',x)` calls?  Silently ignored?

**Comment by arachnetech** [comment]
I've just had a quick look at the code. It should be fine to manipulate the configuration like that, yes. The configuration object passed to the codec is the one used by the mqtt-thing accessory - and the codec is loaded and initialized before any MQTT subscriptions are established.

The documentation for `notify()` is a bit vague: it says "Note that generally a corresponding MQTT 'get' topic must have been configured in order for internal subscribers to exist." There may be exceptions, but I think you'll always need to have defined _something_ for the corresponding get topic in order to update the property internally with `notify()`, as otherwise the required internal dispatch table isn't populated. Any attempt to notify a property not in this dispatch table will be silently ignored. You can use a dummy topic which will never be published as a workaround.

**Comment by jdtsmith** [comment]
Great, thanks.  Very convenient.  I figured I'd need dummy subscriptions.  Pretty easy and well hidden inside the codec.  BTW, would you consider dropping the ".js" requirement if the file exists alongside `config.json` and there is no matching internal codec?  Looks cleaner.

**Comment by jdtsmith** [comment]
Published codec for IKEA Blinds via Zigbee2MQTT: https://github.com/jdtsmith/mqttthing-ikeaBlindZ2M
