### ISSUE TITLE
getOnline = False -> mqttthing still processes commands from homekit

### ISSUE THREAD

**Issue by talan-z** [arachnetech/homebridge-mqttthing#359]
Hi everyone,

First of all, great plugin!

I'm transferring all my devices to MQTT and realized the following:

- Device reported as offline through getOnline = False to mqtttthing
- Button in homekit still enabled (I fully understand that the effect is NOT immediate)
- If button in homekit is pressed, mqttthing processes the command and resends it 3 times.
- Shouldn't this return an error back to homekit instead?

Cheers,
Talan

**Comment by arachnetech** [comment]
I'm not aware of a mechanism to send an offline error back to homebridge/homekit - it only checks seems to check online/offline state at specific times.

**Comment by talan-z** [comment]
Hi,
The issue is not about homekit.
It's about mqttthing still sending MQTT messages to the server, even though it KNOWS that getOnline is false. Shouldn't be the case. I don't want the user to spam MQTT while the device is in fact offline.
A nice add-on would be to report back an error to homekit in case the user interacts with the device and mqttthing knows it is offline. But this is only secondary.

Regards,
Talan

**Comment by arachnetech** [comment]
Once homekit notices that the device is off-line, it won't let you change its state - so I don't think you'll get much 'spamming'.

Is the sending of a these unnecessary MQTT messages causing a problem for your broker or network, or are you just concerned that it might?

I've generally found the bigger problem with online/offline state is when Homekit won't let you control a device which it thinks is offline when it isn't - so I've erred on the side of sending control messages rather than suppressing them.
