### ISSUE TITLE
LWT

### ISSUE THREAD

**Issue by Dalbadel** [arachnetech/homebridge-mqttthing#36]
Hello again :) there were problems with LWT. I don't know if you can influence it or not. After restarting homebridge all mqtt devices write offline. if I reboot the esp device, everything is fine.

**Comment by tobekas** [comment]
Hi, maybe the LWT message with payload=false (offline) was sent with a retained flag. In this case, your MQTT broker will immediately publish this message again, when homebridge subscribes to the getOnline topic (after restarting homebridge). You have to make sure that the message with payload=true (online), your ESP has to send when going online, is also sent with retained flag.

If you do not use retained messages at all, everything should work fine, because the property `getOnline` is initialized with true (=online). Keep in mind: Apple's home app does not update the availability status continuously. You have to reopen the app or switch between rooms to trigger a new request.

**Comment by Dalbadel** [comment]
Hello! as I did not guess ....
The online message had a false retain.
Thank!
You solved my problem.

and I would like to https://github.com/arachnetech/homebridge-mqttthing/issues/38
