### ISSUE TITLE
garagedooropener

### ISSUE THREAD

**Issue by ichbinfabio** [arachnetech/homebridge-mqttthing#46]
Hey,
when I change the garagedoor status externally, i get a notification that says that the door was for example closed, but the button in home kit shows, in this case "opening". So i think it tries to reachieve the state of before changing the door´s status extrenally

**Comment by ichbinfabio** [comment]
Or when it publish opening in getTargetState it says closing in the home app

**Comment by rpolenthon** [comment]
Hey Fabio,
i have the same problem. I will try to switch to the homebridge-mqttgaragedoor Plugin the next days.
I had also the problem that I have to change the source code. I needed different door Values for the different topics. So I changed the standard array values in source code. 

I hope that the developer will continue work on this great plugin in the future. The ability to integrate shutters would also be nice. Do you know a good way to do that?

Have a nice Christmas and get good into the next year!

**Comment by ichbinfabio** [comment]
First, thanks for your wishes :)
So I`ll try to switch to homebridge-mqttgaragedoor too, i´ll tell you if it works better.

**Comment by ichbinfabio** [comment]
I've just tested it (), same problem. 

Just in order to define the problem right, following situation:
garagedoor is open, also displayed open in homekit. Now, when the door is closed throug e.g. a hardware button, that is connected to the garage door, i send "closed" to the "current" mqtt topic. I get a notification that the garagedoor ha been closed, but in the homekit app, it shows the opening animation.

Maybe this is just a bug in apple's home app, and not in the homebridge pluging.

**Comment by rpdever** [comment]
Is this bug also appearing if you force close the app?

**Comment by rpdever** [comment]
Ups.. wrong account.

**Comment by ichbinfabio** [comment]
Ive closed and started the app several times, still same wring animation

**Comment by arachnetech** [comment]
Apple's Home App doesn't like external changes to the state of garage doors or security systems. I made some changes in 1.0.15 to allow external control to the extent that Homekit supports it:

> `getTargetDoorState` - Topic that may be published to notify HomeKit that the target door state has been changed externally. Values are _final_ `doorValues` (not opening/closing). May use same topic as `getCurrentDoorState`. Omit if all control is through HomeKit.

In other words, to support external control you need to change the target door state as well as the current door state - otherwise Homekit doesn't know, and the Home app always assumes that the door will be moving towards the target state that it knows about.

An additional complication is that target door state doesn't support notifications. This means that the Home App will only _notice_ that you've updated the target door state if you close and re-open it (or switch to another app then switch back).

Regarding @rpolenthon's comment re. shutters, I've just added support for 'window coverings'.
