### ISSUE TITLE
Light Bulb RGB setting not correct state

### ISSUE THREAD

**Issue by Kepete** [arachnetech/homebridge-mqttthing#47]
If in the Home app I don't turn on the light bulb but instead long press and then change color, it works, but doesn't show the correct ON/OFF state. The light bulb turns to RED and it shows OFF in home app as the state. 
Mqttthigns should toggle the state to ON as soon as any input is received to change color.

**Comment by tobekas** [comment]
Mqttthig behaves correctly. If the lightbulb is off and you change color from the Home app, the light should stay off, because the Home app does not call the On-characteristic (unlike changing the brightness where On is called, too). Color is saved internally and will be effective the next time you turn it on. 
If your lightbulb is turned on anyway, it should publish a getOn status message, so Mqttthing can update the state correctly.

**Comment by Kepete** [comment]
Yep, my light bulb was turned on anyway. But then it is not an problem of mqttthing 👍 
Issue can be closed.
