### ISSUE TITLE
Request: sent cm2 http or curl

### ISSUE THREAD

**Issue by Luftloch80** [arachnetech/homebridge-mqttthing#85]
Hey,
Would it be possible to implement for a motion sensor that it triggers also a curl or http command when activated 
I wann to Play a mp3 on My Sonos when motion detetected with Sonos http api 
Thx

**Comment by NorthernMan54** [comment]
Isn’t this what an automation is for?

**Comment by Luftloch80** [comment]
Absolut. But automation in HomeKit is sometimes unreliable and not working everytime

**Comment by arachnetech** [comment]
I now run Node-RED (https://nodered.org/) in addition to Homebridge, and can highly recommend it. It can talk MQTT, so it can listen to the topics used by mqttthing devices. I do still use Homekit automations and scenes too, but far more complex automations can be set up in Node-RED and it integrates with many different things. For example we have a room where the light comes on for 5 minutes after opening the door (Xiaomi contact sensor), but also if the TV is turned on.

I've used mqtt-thing to help integrate with Node-RED by defining switches representing which Homekit scene is active. These switches are added to the scenes (so that the scenes turn them on). They use the same 'set' and 'get' topics with different ON values, so that when one scene switch is turned on it automatically turns off all the other scene switches. The ON value is the name of the scene, so Node-RED can subscribe to this topic and know the current scene at all times. I also have switches which trigger the scenes so that Node-RED (and Alexa) can control scenes by turning on these switches. These switches are linked to Homekit automations to enable each scene.
