### ISSUE TITLE
Request: Sprinkler

### ISSUE THREAD

**Issue by desq42** [arachnetech/homebridge-mqttthing#96]
Kudos to your plugin. Would it be possible to implement "Sprinker" as an accessory?

**Comment by tobekas** [comment]
Should be possible...

I think this is `Service.Valve` with the following characteristics:
- Characteristic.Active (it‘s not Characteristic.On??)
- Characteristic.InUse
- Characteristic.ValveType (may be a constant. Possible values: GENERIC_VALVE, IRRIGATION, SHOWER_HEAD or WATER_FAUCET)
Optional:
- Characteristic.SetDuration
- Characteristic.RemainingDuration (timer must be implemented in this plugin, remaining duration should be updated continuously?)
- Characteristic.IsConfigured
- Characteristic.ServiceLabelIndex
   - additional `Service.ServiceLabel` required for each possible index
      - Characteristic.ServiceLabelNamespace
- Characteristic.StatusFault
- Characteristic.Name

but there is also `Service.IrrigationSystem`:
- Characteristic.Active
- Characteristic.ProgramMode (get-only, possible values: NO_PROGRAM_SCHEDULED, PROGRAM_SCHEDULED, PROGRAM_SCHEDULED_MANUAL_MODE)
- Characteristic.InUse
Optional:
- Characteristic.Name
- Characteristic.RemainingDuration
- Characteristic.StatusFault

and there is `Service.Faucet`:
- Characteristic.Active
Optional:
- Characteristic.Name
- Characteristic.StatusFault

**Comment by tobekas** [comment]
According to this description
https://github.com/Colorado4Wheeler/HomeKit-Bridge/wiki/HomeKit-Model-Reference
Valve and Faucet are unsupported by the native Apple Home app. So `Service.IrrigationSystem` might be the right service for this purpose.

**Comment by tobekas** [comment]
Or is Valve the better one?
This Thread is helpful: https://github.com/nfarina/homebridge/issues/1707#issuecomment-388134353

**Comment by Fearraiser** [comment]
I use Valve with home app so well. It has many characteristics and is very user-friendly.

**Comment by tobekas** [comment]
I created pull request #99 to support "valve" (Sprinkler, Shower, Faucet)

@desq42: Hope this will do the job for you.

**Comment by desq42** [comment]
@tobekas wow, thanks for your work.
I´m having an issue with the "getInUse"-Topic. Isn´t it the same as "getActive"?

`[2019-4-21 10:06:30] [BetaSprinkler] Warning: No MQTT dispatch handler for topic [stat/sonoff4ch/POWER1]`

**Comment by tobekas** [comment]
I think „InUse“ is to indicate that water is really flowing, whereas „Active“ means that the valve is opened.
It should not be a problem to use the same topic for both.

„setDuration“ is not for constants, but for a topic (if the sprinkler can handle this). Try „turnOffAfterms“ instead. 

@arachnetech: Or is there an issue with the mqtt dispatcher code, if one topic is configured multiple times?

**Comment by arachnetech** [comment]
One topic used multiple times should be fine - pretty certain I add a new topic use to the existing subscription and call all registered callback functions.

**Comment by desq42** [comment]
```
{
            "accessory": "mqttthing",
            "type": "valve",
            "valveType": "sprinkler",
            "name": "BetaSprinkler",
            "url": "http://10.0.1.3",
            "username": "admin",
            "password": "4711",
            "topics": {
                "setActive": "/cmnd/sonoff4ch/POWER1",
                "getActive": "/stat/sonoff4ch/POWER1",
                "getInUse": "/stat/sonoff4ch/POWER1"
            },
            "turnOffAfterms": 30000,
            "onValue": "ON",
            "offValue": "OFF"
        },
```
Now it works somehow;
When I turn the sprinkler on in the "home-app" the relay is switched on and switchted off after the
the defined period (turnOffAfterms) but the "switch" in the home-app state is "inactive".
It seems as if the home-app get´s no "remain-time" feedback…

<img width="110" alt="Bildschirmfoto 2019-04-22 um 09 42 55" src="https://user-images.githubusercontent.com/18470786/56489758-12f65c80-64e3-11e9-99d5-6bbbb7086bdd.png">
<img width="111" alt="Bildschirmfoto 2019-04-22 um 09 43 04" src="https://user-images.githubusercontent.com/18470786/56489766-18ec3d80-64e3-11e9-8923-27eae5a83555.png">

```
[2019-4-22 09:38:55] [Sprinkler] Warning: No MQTT dispatch handler for topic [stat/sonoff4ch/POWER1]
[2019-4-22 09:39:25] [Sprinkler] Warning: No MQTT dispatch handler for topic [stat/sonoff4ch/POWER1]
```

**Comment by tobekas** [comment]
Your warning shows the get-topic without leading "/" but you added slashed in the config file. This is in fact a different string, so the dispatch handler is not called. It is not recommended to use leading slashes in topics.

**Comment by desq42** [comment]
I removed the leading "/" and now the sprinkler switches on and off.
But I don´t get the remaining time in the home-app. (shows as 0:00)

**Comment by tobekas** [comment]
Hi. I can reproduce this and see the same behavior.

After a little debugging, I found the mistake:
https://github.com/arachnetech/homebridge-mqttthing/blob/cf9c1d3cb075fba9d2526c5d7ed9ce3622fad881/index.js#L1502
It should be `return (state.active && remainingDuration > 0) ? remainingDuration : 0;`
(`state.active` instead of `state.inUse`).

Background: A Change in 'Active' is used to trigger the timer. When getRemainingDuration() is called, 'inUse' may not been updated yet, so it returns 0. It's better to use 'Active' property itself, because it's value is definitively updated. Why is this additional condition used at all? After turning off the sprinkler, the remaining time should disappear in Eve App (in Home App it's ok...), and it disappears, if time is set to 0. So value 0 will be pushed to Homekit, every time you turn off.

@arachnetech: Can you fix this one line for the next release?

**Comment by arachnetech** [comment]
Sure, will do.

**Comment by arachnetech** [comment]
Now in version 1.0.36. Trying to get RGBWW lights working delayed this somewhat - apologies.

**Comment by desq42** [comment]
I upgraded to the new 1.0.36 version. The sprinkler switches off at `"turnOffAfterms": "30000"`
but the remainig time in the home-app is always 60min.

**Comment by tobekas** [comment]
This is because the default HomeKit MaxValue is 3600s. And the values is limited internally to 1h. If we modify this mac value (or make it configurable) this would allow values greater than 1h.

**Comment by tobekas** [comment]
Ah... at the moment you can either use `turnOffAfterms` or `setDuration`. If you use the Homekit duration characteristics, the accessory must handle the off time itself and this duration is shown in the App. It makes sense to add this timer handling to mqttthing, so you may use a "configurable turnOffAfterms". I initially omitted this functionality.

**Comment by nixmeer** [comment]
@desq42 I got the same idea this morning: just ask here if they'd implement sprinkler support but you've been faster... thank you!

**Comment by tobekas** [comment]
Some thoughts about duration functionality...
There are several configuration options:
1. using a fix duration (using `turnOffAfterms`, expected remaining time will be shown)
2. using the HomeKit duration characteristics (timer handled by this plugin) *ToDo, new*
3. using the HomeKit duration characteristics (timer is handled externally, duration topics needed, plugin is showing the expected remaining time)
4. using no timers at all.

If mqttthing should stop the device (send set message false) after the configured duration has expired (variant 2), there is no need for a `setDuration`, `getDuration` or `getRemainingDuration` topic. The two get topics may be added optionally for reporting to other smart home environments. But in this case, the subscribe/publish direction would change. Or do you think this is too exaggerated or unclear functionality? Otherwise these topics could be ignored or optionally used in the same way as variant 3. To keep things simple, I suggest using them the same way as variant 3:
- `setDuration`: mqttthing publishes to it, when duration is changed within Homekit App.
- `getDuration`: mqttthing subscribes to it and updates the configured duration, if a message is received. If updated while valve was already active, it applies the difference between last and new value to the remaining duration. (e.g. 14min remaining: A change from 15 to 10min will result in 9min remaining)
- `getRemainingDuration`: mqttthing subscribes to it and updates the remaining time, if a message is received. It can be used to update the homekit characteristic directly, for example if the external timer is modified. For variant 2 this can be used to reset the timer to a specific value via MQTT.

I also suggest adding another config entry like `durationTimer = true` (or alternatively setting `turnOffAfterms = "configurable"`) for enabling the internal turn-off-timer. Default may be true or false?

Some information about HomeKit’s remaining time characteristic:
- remaining time will be updated once when valve is activated (Home App is counting down by itself) and it must return the correct remaining time for every new request (reopen App, change room page, ...)

@arachnetech and others: What is your opinion?

I could possibly deal with it today or tomorrow evening and make a proposal (pull request).

**Comment by nixmeer** [comment]
hello,

I got another question: homebridge-mqtt-sprinkler (which does not work obviously) wants the mm/Liters to be published by the device. Is there any characteristic to show the throughput in the home app? 
I got a bucket on the balcony and I’d like to see how much of the 10 liters has been used

**Comment by tobekas** [comment]
This is part of fakegato-history (mimic of Eve Aqua) and is only working within the Eve App. Maybe this could be implemented later, but first goal is to get to a simple and stable basic function.

**Comment by arachnetech** [comment]
@tobekas Regarding your question above (although I haven't actually used the sprinkler myself, so I may well be misunderstanding how it works)...

I think it would be helpful to have a way to specify the duration and then see the remaining duration updating correctly in homekit without having to calculate and publish remaining duration in the device itself. I think the most natural way would be for mqttthing to calculate and update the remaining duration (to homekit, and perhaps also by publishing it to the `setRemainingDuration` topic if configured) if the device doesn't want to publish remaining duration regularly. You could do this with a new `durationTimer` option as you suggest, or perhaps more simply you could just do this if no `getRemainingDuration` topic is configured?

**Comment by tobekas** [comment]
Ok... I‘m done with the timer implementation (see my fork). I did not create a pull request yet since it it not automatically mergable at the moment due to latest changes.

I will update my code based on the current master, ok?

**Comment by arachnetech** [comment]
Yes please, that would be great

**Comment by tobekas** [comment]
Ok... no problem: Here you are, Pull Request #110.

With this update, `setDuration`, `getDuration` or `getRemainingDuration` topics are not needed any more. You just need to add `"durationTimer": true` to the config.json

The topics can still be used optionally.

**Comment by desq42** [comment]
…yeah! Works as expected. Kudos to @tobekas.
Perhaps add one minor enhancement;
` "turnOffAfterms": "1200000",`
Change the "turnOff"-Timer to seconds or minutes.

**Comment by tobekas** [comment]
`turnOffAfterms` is not really suitable for this sprinkler application. You do not need it anymore. just add `"durationTimer": true`. You can choose your desired duration in the Home-App sprinkler settings.
The turnOff-implementation is very generic and for other types, e.g. Switch, it makes perfect sense.

**Comment by desq42** [comment]
👍🏻😀

**Comment by nixmeer** [comment]
I got one more question about sprinklers in HomeKit:

Is there any way to automate them? I’d like to aktivste them at a specific time or at sensor events. But sprinklers are not shown when creating automations ...

**Comment by tobekas** [comment]
Unfortunately it does not seem to be possible right now to use this type in Apple Home automations. 

see https://github.com/RavenSystem/esp-homekit-devices/issues/316
